# 预约后天座位，时段 7:00–22:00。

周一:
  启用: true
  name: 二楼西  # 见 config/seat_config.yml
  开始时间: 7
  持续小时数: 15
周二:
  启用: true
  name: 二楼西
  开始时间: 7
  持续小时数: 15
周三:
  启用: true
  name: 二楼西
  开始时间: 7
  持续小时数: 15
周四:
  启用: true
  name: 二楼西
  开始时间: 7
  持续小时数: 15
周五:
  启用: true
  name: 二楼西
  开始时间: 7
  持续小时数: 15
周六:
  启用: true
  name: 二楼西
  开始时间: 7
  持续小时数: 15
周日:
  启用: true
  name: 二楼西
  开始时间: 7
  持续小时数: 15


# 注：若要开启自定义功能，需将name改为“自定义”
# 如无特殊需求（如固定座位），只需填对应自习室名称，
# 无需修改自定义中内容。

自定义:
    - 10000
    - 10001


# 可选 name：
# 自习室：二楼西/比特庭园（二楼西）、二楼东/格物E堂（二楼东）、二楼信息检索室/数智渊阁（二楼 信息检索室）、十二楼/芯灵驿站（十二楼）
# 生活区：求新书院、守正书院
# 阅览室：三楼东、三楼西、三楼北、七楼、八楼、九楼、十楼、十一楼
